version: '3'
services:
  aidev:
    image: dak00/aidev:pytorch2.1.2-cu12.1-devel
    container_name: aidev
    ipc: host
    command: tail -f /dev/null
    ports:
      - 8888:8888
    volumes:
      - ${HOME}/.cache/huggingface:/home/dom/.cache/huggingface
      - .:/home/dom/workspace
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
